### ISSUE TITLE
Floder path

### ISSUE THREAD

**Issue by ihsanenginbal** [onuarslan/readingalltxtfile#1]
Floder path'leri böyle mi vermen gerekiyor her seferinde? Bu çok zor olur. Bulunduğun klasörün içine refere demiyor musun direk? Matlab'da mümkün. Klasörü başka yere taşısın da, py dosyasının olduğu yeri ana folder kabul etmesi lazım. Bir bak ona. Hayatını çok kolaylaştırır.

folder_path = '/Users/onur/Desktop/TDG_PIY/Nederboom_test_finalruns/Data/'

**Comment by ahmetanildindar** [comment]
Dear all,
Full path yerine relative path vermenizi öneririm :)

`folder_path = './Nederboom_test_finalruns/Data/'`

veya

`folder_path = os.getcwd() + './Nederboom_test_finalruns/Data/'`

---
Bir de path stringlerin önüne r koymanızı öneririm. 

Örnek: 
`folder_path = os.getcwd() + r'./Nederboom_test_finalruns/Data/'`

**Comment by ihsanenginbal** [comment]
Teşekkürler @ahmetanildindar . 
@onuarslan , buna bakıp kodu yeniden düzenler misin müsait olunca?
